name: Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build Vue app
      working-directory: client
      run: |
        npm install
        npm run build

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: instagram
        resource-group: instagram_new
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          