name: Build and deploy Python app to Azure Web App - instagram

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: instagram
  AZURE_RESOURCE_GROUP: YOUR_RESOURCE_GROUP_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make startup.sh executable
      run: chmod +x startup.sh

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Changed to supported version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build Vue app
      working-directory: client
      run: |
        npm install
        npm run build

    - name: Zip artifact
      run: zip -r release.zip . -x 'venv/*' 'client/node_modules/*'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Unzip artifact
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        package: .